language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      
install:
  - pip install pygame
  - pip install numpy
  - pip install coveralls
  
script:
  - python balls.py
  - python test_balls.py
after_success:
  - coveralls